### ISSUE TITLE
Analytics investigation

### ISSUE THREAD

**Issue by kebrahim** [ny/maslow-experimental#9]
- [x] Determine what framework NYS is already using
- [x] Document how would we use that framework in Maslow design doc
- [ ] Prototype of using that Google Analytics tag (assuming they use that) in experimental

**Comment by itssumertime** [comment]
Synced with Isaac who said that analytics can easily be integrated into New York State's existing Google Analytics, and he'll provide us with code snippets to include for adding analytics once we have some basic mocks/implementation ready.
